name: green2get_shared_modules
description: A package for Green2Get apps.
version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.3
  build_runner: ^2.4.7
  get: ^4.6.6

flutter:
  assets:
    - example/picsum.photos/
